# Also see:
#   Dockerfile
#
# https://docs.docker.com/compose/compose-file/compose-file-v3/

version: "3.6"

services:

  static:
    build: .
    command: sh -c "
      echo 'Starting static webserver at http://127.0.0.1:8080/'
      && httpd-foreground
      "
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./config:/usr/local/apache2/conf/config:ro
      - ./src:/usr/local/apache2/htdocs:ro
